#!/usr/bin/env python3
"""Extract the real prompt-composing declarations from TransformService.swift,
verbatim, into a standalone Swift program that prints every composed prompt as
JSON. The point is that the bytes measured are printed by the *real* code, not
by a Python reconstruction: the extraction is mechanical (declaration span, brace
matched) and the output is compared byte-for-byte against the Python harness.

Usage: build-prompt-harness.py <TransformService.swift> <out main.swift>
"""
import sys


def span(text, decl):
    """The declaration starting at `decl`, brace-matched to its closing brace."""
    start = text.index(decl)
    # back up to the start of the line, so the indentation comes along
    line_start = text.rindex("\n", 0, start) + 1
    brace = text.index("{", start)
    depth = 0
    i = brace
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[line_start:i + 1]
        i += 1
    raise SystemExit(f"unbalanced braces after {decl!r}")


def main():
    src_path, out_path = sys.argv[1:3]
    src = open(src_path, encoding="utf-8").read()

    parts = [
        "// GENERATED by build-prompt-harness.py — declarations extracted VERBATIM from",
        f"// {src_path}",
        "// Do not edit: re-run the extractor instead.",
        "import Foundation",
        span(src, "enum ToneMode"),
        span(src, "enum TransformLanguage"),
        span(src, "enum TransformPolicy"),
        "final class TransformService {\n"
        + "\n\n".join([
            span(src, "static func systemPrompt"),
            span(src, "static func toneInstruction"),
            span(src, "static func polishMarkerInstruction"),
            span(src, "private static func englishToneInstruction"),
            span(src, "static func polishToneInstruction"),
            span(src, "static func userPrompt"),
            span(src, "private static func englishUserPrompt"),
            span(src, "static func cleanUpInstruction"),
            span(src, "static func referenceInstruction"),
        ])
        + "\n}",
        r'''
// Every prompt the tone path can send, for every (language, register), plus the
// clean-up-alone wording and the reference block. Printed as JSON so the
// comparison below is byte-exact.
var systems: [String: String] = [:]
for language in TransformLanguage.allCases {
    for tone in ToneMode.allCases {
        systems["tone/\(language.rawValue)/\(tone.rawValue)"] = TransformService.systemPrompt(
            for: .tone(language: language, tone: tone), cleanUp: false)
        systems["cleanUpWithTone/\(language.rawValue)/\(tone.rawValue)"] = TransformService.systemPrompt(
            for: .cleanUpWithTone(language: language, tone: tone), cleanUp: true)
    }
    systems["cleanUp/\(language.rawValue)"] = TransformService.systemPrompt(
        for: .cleanUp(language: language), cleanUp: true)
}

var users: [String: String] = [:]
let probe = "wyślij raport do klienta dzisiaj"
let probeEn = "send the report to the client today"
for language in TransformLanguage.allCases {
    for tone in ToneMode.allCases {
        users["\(language.rawValue)/\(tone.rawValue)"] = TransformService.userPrompt(
            for: language == .polish ? probe : probeEn, language: language, tone: tone)
    }
}
let reference = TransformService.systemPrompt(
    for: .tone(language: .polish, tone: .formal), cleanUp: false,
    reference: "Docker, Qwen, Kraków")

let payload: [String: Any] = ["systems": systems, "users": users,
                              "referenceBlock": reference,
                              "probe": probe, "probeEnglish": probeEn]
let data = try JSONSerialization.data(withJSONObject: payload, options: [.sortedKeys])
FileHandle.standardOutput.write(data)
print()
''',
    ]

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n\n".join(parts) + "\n")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
